### ISSUE TITLE
Add selectable license?

### ISSUE THREAD

**Issue by walkerh** [conda/cookiecutter-conda-python#11]
Should this cookiecutter add a selectable license similar to [`audreyr/cookiecutter-pypackage`](/audreyr/cookiecutter-pypackage)? It would be easy enough for me to fabricate the necessary template.

**Comment by TejasAvinashShetty** [comment]
Any progress?

**Comment by AlbertDeFusco** [comment]
This was added in #14 . It will now provide you with the option to select from a few of the most common licenses

```
Select open_source_license:
1 - MIT
2 - BSD
3 - ISC
4 - Apache
5 - GNUv3
6 - Proprietary
Choose from 1, 2, 3, 4, 5, 6 [1]:
```
