### ISSUE TITLE
failing to setup

### ISSUE THREAD

**Issue by zainmdm** [conda/cookiecutter-conda-python#12]
I am unable to setup this project with after installed using conda 2 and python 2.7

after running the below, its just returning back to the prompt, please suggest
$ cookiecutter https://github.com/drivendata/cookiecutter-data-science

zainmdm@DESKTOP-D0AN22H MINGW64 /d/zain_python/gitcode (master)
$ echo $?
1

**Comment by walkerh** [comment]
Are you sure you put this issue in the correct repo?

This repo is "cookiecutter-conda-python" not "cookiecutter-data-science". Also, I had no trouble building "example_project" using "cookiecutter-data-science" and cookiecutter running under Python 2.7. (Admittedly my root environment was Anaconda 3.)

**Comment by zainmdm** [comment]
thanks for your response , Apologies , I will post in cookiecutter data science

**Comment by TejasAvinashShetty** [comment]
@zainmdm Please close the issue if you done with it.
