### ISSUE TITLE
Failed CLI test

### ISSUE THREAD

**Issue by amcruise** [conda/cookiecutter-conda-python#24]
============================= test session starts ==============================
platform darwin -- Python 3.8.5, pytest-6.1.0, py-1.9.0, pluggy-0.13.1
rootdir: $SRC_DIR
plugins: cov-2.10.1
collected 1 item

tests/test_cli.py F                                                      [100%]

=================================== FAILURES ===================================
______________________________ test_cli_template _______________________________

    def test_cli_template():
>       assert cli.cli() is None

tests/test_cli.py:4: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/site-packages/pieparty/cli.py:16: in cli
    args = p.parse_args(args)
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/argparse.py:1771: in parse_args
    self.error(msg % ' '.join(argv))
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/argparse.py:2521: in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = ArgumentParser(prog='pytest', usage=None, description='scRNA visualization tool', formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='resolve', add_help=True)
status = 2, message = 'pytest: error: unrecognized arguments: tests\n'

    def exit(self, status=0, message=None):
        if message:
            self._print_message(message, _sys.stderr)
>       _sys.exit(status)
E       SystemExit: 2

../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/argparse.py:2508: SystemExit
----------------------------- Captured stderr call -----------------------------
usage: pytest [-h] [-V]
pytest: error: unrecognized arguments: tests
=========================== short test summary info ============================
FAILED tests/test_cli.py::test_cli_template - SystemExit: 2
============================== 1 failed in 0.17s ===============================

**Comment by amcruise** [comment]
meta.yaml file contains:

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
  commands:
    - **pytest tests**

And setup.cfg contains:

[flake8]
max-line-length = 100
ignore = E122,E123,E126,E127,E128,E731,E722
exclude = build,pieparty/_version.py,conda.recipe,tests,.git,versioneer.py,benchmarks,.asv

[tool:pytest]
norecursedirs= .* *.egg* build dist conda.recipe
addopts =
    --junitxml=junit.xml
    --ignore setup.py
    --ignore run_test.py
    --cov-report term-missing
    --tb native
    --strict
    --durations=20
env =
    PYTHONHASHSEED=0

Could this error be caused by setup.cfg excluding tests which can therefore not be used as an argument in the command:  pytest tests?

**Comment by amcruise** [comment]
Worked around it.

**Comment by ponderapython** [comment]
Hi amcruise. I get the same error. How did you work around it?

**Comment by amcruise** [comment]
Hi! So I gave up on cookie cutter, I followed anaconda documentation to build my own recipe. It took some time to implement and learn what is doing what, but it become relatively. Sorry I wasn’t able to help in implementing cookie cutter!



Sent from my iPhone

On Nov 18, 2020, at 4:11 AM, ponderapython <notifications@github.com> wrote:

﻿

      External Email - Use Caution



Hi amcruise. I get the same error. How did you work around it?

**Comment by giftmischer69** [comment]
Hi! Maybe this will help @ponderapython 
https://github.com/conda/cookiecutter-conda-python/issues/25#issuecomment-770356565

**Comment by rdmolony** [comment]
Had the same issue.  It seems that when running `pytest tests` or `pytest tests --pdb` the arguments after `pytest` are being added by `ArgumentParser` to `args`:

```python-traceback
> /home/wsl-rowanm/Code/ber-public/ber_public/cli.py(18)cli()
-> args = p.parse_args(args)
(Pdb) locals()
{'args': None, 'p': ArgumentParser(prog='pytest', usage=None, description="A Python toolkit for the SEAI's BER public dataset ", formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='resolve', add_help=True)}
(Pdb) d
> /home/wsl-rowanm/mambaforge/envs/ber/lib/python3.9/argparse.py(1821)parse_args()
-> self.error(msg % ' '.join(argv))
(Pdb) locals()
{'self': ArgumentParser(prog='pytest', usage=None, description="A Python toolkit for the SEAI's BER public dataset ", formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='resolve', add_help=True), 'args': Namespace(), 'namespace': None, 'argv': ['tests', '--pdb'], 'msg': 'unrecognized arguments: %s'}
> /home/wsl-rowanm/mambaforge/envs/ber/lib/python3.9/argparse.py(2575)error()
-> self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
(Pdb) locals()
{'self': ArgumentParser(prog='pytest', usage=None, description="A Python toolkit for the SEAI's BER public dataset ", formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='resolve', add_help=True), 'message': 'unrecognized arguments: tests --pdb', 'args': {'prog': 'pytest', 'message': 'unrecognized arguments: tests --pdb'}}
```

---

*"parse_args method, when it's called without arguments, attempts to parse content of sys.argv. Your interpreter process had filled sys.argv with values that does not match with arguments supported by your parser instance, that's why parsing fails."*
> ... source: [SystemExit: 2 error when calling parse_args()](https://stackoverflow.com/questions/42249982/systemexit-2-error-when-calling-parse-args):

Replace:
`args = parser.parse_args()`
with
`args, unknown = parser.parse_known_args()`
> ... source: [Python argparse ignore unrecognised arguments](https://stackoverflow.com/questions/12818146/python-argparse-ignore-unrecognised-arguments)
