### ISSUE TITLE
Example entry point outputs to stderr and returns an error to the OS

### ISSUE THREAD

**Issue by walkerh** [conda/cookiecutter-conda-python#7]
The file cli.py implements the one entry point which returns a string.

See: https://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation

> … their return value is passed to sys.exit(), so you can return an errorlevel or message to print to stderr.

Thus the affect of calling the command from a terminal is to print to stderr rather than stdout and also return an error level of 1.

Since this is the only example with no indication that it is supposed to constitute an error, I propose something more like this:

```
def cli():
    print("CLI template")
    # Return a value of 1 or higher to signify an error; 0 or None means good.
    return  # See https://docs.python.org/3/library/sys.html#sys.exit
```

**Comment by mandeep** [comment]
Thanks for reporting this. I agree that the cli function should print a message rather than returning one. However, I'm not sure I agree with the empty return statement. Instead, I think we could just leave off the return since omitting it will return None all the same.

**Comment by walkerh** [comment]
How about this then:

```
def cli():
    print("CLI template")
    # No return value means no error.
    # Return a value of 1 or higher to signify an error.
    # See https://docs.python.org/3/library/sys.html#sys.exit
```

**Comment by mandeep** [comment]
Sure. Do you mind submitting a PR?

**Comment by walkerh** [comment]
No problem. I'll get you the PR today or tomorrow.

For the test, I'll just `assert cli.cli() is None`.

**Comment by walkerh** [comment]
Merging PR #8 fixed this. Closing.
